services:
  frontend:
    build:
      context: ./docker/frontend
    working_dir: /app
    volumes:
      - ./app:/app:delegated
      - node_modules:/app/node_modules
      - npm_cache:/root/.npm
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    command: ["/bin/sh", "/entrypoint.sh"]

  api:
    build:
      context: ./docker/api
    volumes:
      - ./data:/data
    ports:
      - "3001:3001"
    command: ["sh", "-c", "json-server --watch /data/db.json --host 0.0.0.0 --port 3001"]

volumes:
  node_modules:
  npm_cache:
